version: '3.8'

services:

  # Node server to run typescript
  node_server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: node_server
    hostname: node_server
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app
    ports:
      - 3000:3000
    command: bash -c "npm install && npm run dev"
